check50: 
  files:
    - !exclude "*"
    - !include "*.py"
    - !require "hello_name.py"

  checks:
    single name:
      - run: python3 hello_name.py
        stdin: "Heiner"
        stdout: "Hello, Heiner"
        exit: 0
    full name:
      - run: python3 hello_name.py
        stdin: "james BOND"
        stdout: "Hello, james BOND"
        exit: 0  
